import { Status } from "./api-response.model";

// FARES
export interface Fare {
  id: string;
  organizationId: string;
  fareCode: string;
  fareName: string;
  fareType: FareType;
  fareAmount: number;
  status: Status;
  createdAt: string | number; // Instant type in backend (can be ISO string or epoch seconds)
  effectiveDate: string | number; // Instant type in backend (can be ISO string or epoch seconds)
}

// Respuesta del backend que incluye objeto completos
export interface EnrichedFareResponse {
  id: string;
  organizationId: string;
  organizationName: string;
  fareCode: string;
  fareName: string;
  fareType: string;
  fareAmount: number;
  status: string;
  createdAt: string | number; // Instant type in backend (can be ISO string or epoch seconds)
  effectiveDate: string | number; // Instant type in backend (can be ISO string or epoch seconds)
}

// Solicita creación de tarifa según el backend AdminRest.java
export interface FareCreateRequest {
  organizationId: string;
  fareName: string;
  fareType: string;
  fareAmount?: number;
  // effectiveDate is auto-generated by backend
}

// ENUMS
export enum FareType {
  SEMANAL = 'SEMANAL',
  MENSUAL = 'MENSUAL',
  ANUAL = 'ANUAL'
}

export const FareTypeLabels = {
  [FareType.SEMANAL]: 'Semanal',
  [FareType.MENSUAL]: 'Mensual',
  [FareType.ANUAL]: 'Anual'
};

export interface Organization {
  organizationId: string;
  organizationCode: string;
  organizationName: string;
}

export interface User {
  userId: string;
  firstName: string;
  lastName: string;
}
